name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/cachix-action@v15
      with:
        name: please-cli
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
